### ISSUE TITLE
Document `unsafe` with `SAFETY` comments and warn about usage of `unsafe` in README

### ISSUE THREAD

**Issue by simonsan** [wyfo/swap-buffer-queue#1]
From [reddit](https://www.reddit.com/r/rust/comments/14jasc6/comment/jpkr35z/?utm_source=reddit&utm_medium=web2x&context=3):

> amarao_san
> I checked few places, and I see a lot of unsafe code which I have trouble to understand. May be I'm not that bright, but you don't have any SAFETY comments there proving to readers that it's safe to have unsafe in safe code. If you want your library to be really reviewed, you need to write proofs for each unsafe part. "SAFETY: We can do it because of this, and this, and it will uphold invariant which compiler can't check but we know because ..."

> kinoshitajona
> 1. unsafe blocks should have a Safety comment explaining how you uphold the invariants required for this unsafe code usage.
> 1. unsafe fn or traits should have a Safety comment explaining what invariants the user must uphold.

https://std-dev-guide.rust-lang.org/documentation/safety-comments.html

https://rust-lang.github.io/api-guidelines/documentation.html#c-failure

Furthermore, I think it's good to warn users in README about the usage of unsafe in the library, so they are able to make a decision on if they want to pull `unsafe` code as a dependency.

**Comment by wyfo** [comment]
Code should use `#![forbid(clippy::undocumented_unsafe_blocks)]`, see [reddit](https://www.reddit.com/r/rust/comments/14jasc6/comment/jpky0qc)

**Comment by wyfo** [comment]
I think I will also add `#![deny(unsafe_op_in_unsafe_fn)]`. 
```
error: could not compile `swap-buffer-queue` (lib) due to 66 previous errors
```
Ok, that's a lot ...
